# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Technical Art
title_seperator: |
subtitle: WIP
email: eric@totallywickedgames.com
description: >- # this means to ignore newlines until "baseurl:"
  Eric Fear is a Technical Artist from Sydney, Australia working in the video game industry. Specialising in Unreal Engine, Rigging/Animation tools, pipeline, and art leadership.
twitter_username: ericfear
facebook_username: ericfear
github_username: ericfear
minimal_mistakes_skin: dark
search: true
repository: ericfear/ericfear.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

atom-feed:
  hide: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Eric Fear"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Technical Artist for video games."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.ericfear.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ericfear/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ericfear/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ericfear/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ericfear/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ericfear/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ericfear/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "giscus"
  giscus:
    repo_id: R_kgDOGnLq_A
    category_name: Announcements
    category_id: DIC_kwDOGnLq_M4CAkBU
    mapping: title
    reactions_enabled: 1
    emit-metadata: 0
    theme: transparent_dark
    lang: en

twitter:
  username: twitter_username

facebook:
  app_id: 295587899197964
  publisher: https://www.facebook.com/ArtofFear
  username: facebook_username

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-ZYNSZKPWMG"
    anonymize_ip: false # default

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
